blog/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get "home/index"
  root "home#index"
  resources :articles
  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"
end

blog/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # for any visitor or user
    can :read, Article
    if user
      if user.admin?
        # admins can do any action on any model or action
        can :manage, :all
      else
        # regular users can read all content
        can [:edit, :destroy, :read], @articles, user_id: user.id
        # and edit, update and destroy their own user only
        can [:edit, :destroy, :read], User, id: user.id
        can :create, Article
        # but cannot read hidden articles
      end
    else
      # only unlogged visitors can visit a sign_up page:
      can :new, User
    end
  end
end

blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blog/app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, :presence => true, :uniqueness => true, :length => { :maximum => 100 }
  validates :author, :presence => true, :uniqueness => false, :length => { :maximum => 100 }
end

blog/app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  has_secure_password
  validates :email, presence: true, uniqueness: true, :length => { :maximum => 100 }, format: { with: URI::MailTo::EMAIL_REGEXP }
  Roles = [:admin, :client]

  def is?(requested_role)
    self.role == requested_role.to_s
  end

  enum role: [:guest, :client, :admin]

  after_initialize do
    if self.new_record? && self.role == nil
      self.role ||= :client
    end
  end
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  load_and_authorize_resource

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      redirect_to @article
    else
      render "new"
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def index
    @articles = Article.all
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render "edit"
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :author, :text)
  end
end

blog/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

blog/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  # GET /users
  # GET /users.json
  def index
    if current_user.present? && current_user.role == "admin"
      @users = User.all
    else
      flash[:error] = "You are not authorized to access this page."
      redirect_to root_path
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "User was successfully created."
      redirect_to root_path
    else
      flash[:error] = "Error user was not created."
      redirect_to singup_path
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/helpers/home_helper.rb
module HomeHelper
end

blog/app/helpers/sessions_helper.rb
module SessionsHelper
end

blog/app/helpers/users_helper.rb
module UsersHelper
end

blog/app/views/articles/edit.html.erb
<h1>Edite article</h1>

<%= form_for @article, url: article_path do |f| %>

<p>
  <%= f.label :title %><br />
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :text %><br />
  <%= f.text_area :text %>
</p>

<p>
  <%= f.submit %>
</p>

<% end %> 

<%= link_to 'Back', articles_path %>

blog/app/views/articles/index.html.erb
<div class="div-title">
  <h1 class="title">list of all article</h1>
</div>

<table class="table table-dark">
  <tr>
    <th>n°</th>
    <th>Title</th>
    <th>Author</th>
    <th>Text</th>
    <th>Time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% @number = 0 %>
  <% @articles.each do |article| %>
  <tr>
    <td><%= @number += 1 %></td>
    <td><%= article.title %></td>
    <td><%= article.author %></td>
    <td><%= article.text %></td>
    <td><%= article.created_at %></td>
    <td>
      <button class="btn btn-info btn-article">
        <%= link_to 'Show', article_path(article) %></td>
      </button>
    </td>
    <td>
        <% if current_user.present? && current_user.role == "admin" || current_user.present? && current_user.id == article.user_id %>
      <button class="btn btn-success btn-article">
        <%= link_to 'Edit', edit_article_path(article) %>
      </button>
      <% end %>
    </td>
    <td>
        <% if current_user.present? && current_user.role == "admin" || current_user.present? && current_user.id == article.user_id %>
        <button class="btn btn-danger btn-article"><%= link_to 'Destroy', article_path(article), method: :delete, data: {
          confirm: 'are you sure?' } %>
        </button>
        <% end %>
    </td>
  </tr>
  
  <% end %>
</table>
<button class="btn btn-primary btn-article">
  <%= link_to 'New', new_article_path(@article) %>
</button>

blog/app/views/articles/new.html.erb
<div class="form-style-8">
  <h1>New Article</h1>
  
  <%= form_for :article, url: articles_path do |f| %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title, required: true%>
  </p>
  
  <p>
    <%= f.label :auhtor %><br />
    <%= f.text_field :author, required: true %>
  </p>
  
  <p>
    <%= f.label :text %><br />
    <%= f.text_area :text %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
  <%end%>
</div>

blog/app/views/articles/show.html.erb
<h1>Show page</h1>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @article.author %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<p>
  <strong>Time:</strong>
  <%= @article.created_at %>
</p>

<p>
  <%= link_to 'Articles', articles_path(@articles) %>
</p>

blog/app/views/home/index.html.erb
<% if current_user %>
      Logged in as <%= current_user.email %>.
    <% end %>
    <% if  current_user.present? && current_user.role == "admin" %>
    <p>admin</p>
  </div>
  <% end %>
<div class="container">
  <div class="container-index">
    <p id="notice"><%= notice %></p><h1>Welcome</h1>
    <p>My name is Maximus Decimus Meridius, Commander of the Armies of the North, General of the Felix Legions, loyal servant to the true emperor, 
      Marcus Aurelius. Father to a murdered son, husband to a murdered wife. And I will have my vengeance, in this life or the next.</p>
</div>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> 
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag	'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  </head>
    <body>
      <nav class="navbar navbar-inverse navbar-top navbar-fixed-top">
        <div class="container-fluid">
          <div class="container">
            
            <div class="navbar-header">
              
           <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
             <span class="sr-only">Toggle navigation</span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
           </button>
           <a class="navbar-brand" href="/">Tortuga</a>
         </div>
         <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">menus <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Article", articles_path %></li>
                  <% if current_user.present? && current_user.role == "admin" %>

                  <li><%= link_to "Manage Users", users_path %></li>
                  <% end %>
                </ul>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <% if user_signed_in? %>
                    <li><%= link_to "Edit profile", edit_user_path(current_user) %></li>
                    <% else %>
                    <li><%= link_to "Sign up", signup_path %></li>
                    <li><%= link_to "Login", login_path %></li>
                    <% end %>
                    <% if user_signed_in? %>
                    <li role="separator" class="divider"></li>
                    <li><%= link_to "Logout", logout_path %></li>
                    <% end %>
                  </ul>
                </li>
              </ul>
          </div>
          </div>
        </div>
      </nav>
      <div id="main-container" class="container">
          <div class="error"><%= flash[:success] %></div>
          <div class="error"><%= flash[:error] %></div>
          <div class="error"><%= flash[:alert] %></div>

        <%= yield %>
      </div>

    
  </body>
</html>

blog/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <!-- <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
      
      <% user.errors.full_messages.each do |message| %>
        <p class="error"><%= message %></p>
      <% end %>
    </div>
  <% end %> -->
  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  
  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>
  <% if current_user.present? && current_user.role == "admin" %>
  <div class="field">
      <%= form.label :roles %>
      <select name="roles" id="roles">
        <option value="1" selected="selected">Client</option>
        <option value="2">Admin</option>
      </select>
    </div>
<% end %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

blog/app/views/users/edit.html.erb
<div class="form-style-8">
    <h1>Editing User</h1>
    
    <%= render 'form', user: @user %>
    <button><%= link_to 'Show', @user %></button>
    <button><%= link_to 'Back', users_path %></button>
    
</div>

blog/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table table-dark">
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><button class="btn btn-info btn-article"><%= link_to 'Show', user %></button></td>
        <td><button class="btn btn-success btn-article"><%= link_to 'Edit', edit_user_path(user) %></button></td>
        <td><button class="btn btn-danger btn-article"><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

blog/app/views/users/new.html.erb
<div class="form-style-8">
    <h1>New User</h1>
    
    <%= render 'form', user: @user %>
    <%= link_to 'Back', users_path %>
</div>

blog/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>